"""initial schema

Revision ID: 854275aa3632
Revises: 
Create Date: 2026-08-07 11:35:23.964073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'external_id', name='uq_account_broker_external')
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('secid', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('asset_class', sa.String(length=32), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('face_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_isin'), 'instrument', ['isin'], unique=True)
    op.create_index(op.f('ix_instrument_secid'), 'instrument', ['secid'], unique=False)
    op.create_index(op.f('ix_instrument_ticker'), 'instrument', ['ticker'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('op_type', sa.String(length=24), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_transaction_source_external')
    )
    op.create_index('ix_transaction_account_executed', 'transaction', ['account_id', 'executed_at'], unique=False)
    # ### end Alembic commands ###

    # Журнал операций (transaction) — append-only: UPDATE и DELETE запрещены триггером
    # БД, исправления вносятся корректирующими операциями. SQL продублирован буквально
    # в app/models/transaction.py (event.listen на after_create) — там он нужен для
    # тестовой схемы, которая собирается через Base.metadata.create_all и эту миграцию
    # не видит. Миграция намеренно не импортирует код приложения, поэтому дубль текстом,
    # а не общей функцией. Меняешь один текст — обязательно правь оба.
    op.execute(
        """
        CREATE FUNCTION transaction_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'Журнал операций неизменяем: UPDATE и DELETE запрещены, исправления вносятся корректирующими операциями';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER transaction_append_only_trigger
        BEFORE UPDATE OR DELETE ON transaction
        FOR EACH ROW EXECUTE FUNCTION transaction_append_only();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Триггер и функция снимаются до drop_table, чтобы миграция была самодостаточной
    # и не полагалась на каскадное удаление вместе с таблицей.
    op.execute('DROP TRIGGER IF EXISTS transaction_append_only_trigger ON "transaction"')
    op.execute("DROP FUNCTION IF EXISTS transaction_append_only()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_account_executed', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_instrument_ticker'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_secid'), table_name='instrument')
    op.drop_index(op.f('ix_instrument_isin'), table_name='instrument')
    op.drop_table('instrument')
    op.drop_table('account')
    # ### end Alembic commands ###
