"""dedup key

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-07 12:48:45.937115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('dedup_key', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_transaction_dedup_key'), 'transaction', ['dedup_key'], unique=False)
    op.create_unique_constraint('uq_transaction_dedup_key', 'transaction', ['dedup_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_dedup_key', 'transaction', type_='unique')
    op.drop_index(op.f('ix_transaction_dedup_key'), table_name='transaction')
    op.drop_column('transaction', 'dedup_key')
    # ### end Alembic commands ###
