"""price table

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-07 14:25:34.507472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'on_date', name='uq_price_instrument_date')
    )
    op.create_index(op.f('ix_price_instrument_id'), 'price', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_price_on_date'), 'price', ['on_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_on_date'), table_name='price')
    op.drop_index(op.f('ix_price_instrument_id'), table_name='price')
    op.drop_table('price')
    # ### end Alembic commands ###
