"""daily snapshot

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-07 22:52:24.228544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('by_asset_class', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('by_account', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('on_date', name='uq_snapshot_date')
    )
    op.create_index(op.f('ix_daily_snapshot_on_date'), 'daily_snapshot', ['on_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_snapshot_on_date'), table_name='daily_snapshot')
    op.drop_table('daily_snapshot')
    # ### end Alembic commands ###
