"""scope external id uniqueness per account

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-08 00:15:01.037818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    uq_transaction_source_external был (source, external_id) — глобальным по
    источнику. Живая синхронизация показала: T-Invest переиспользует один и тот же
    internal id для двух РАЗНЫХ записей на РАЗНЫХ счетах одного владельца (например,
    обе стороны перевода между своими счетами делят общий идентификатор — разбор в
    fix-ledger-unique-report.md). Такая пара — не дубль, но старое ограничение ложно
    считало её дублем и ронял весь батч синхронизации второго счёта. Область действия
    сужена до счёта: (account_id, source, external_id). Существующие данные не
    нарушают новое, более узкое ограничение — оно строго слабее старого (любая пара,
    уникальная по (source, external_id), остаётся уникальной и по (account_id, source,
    external_id)).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_transaction_source_external'), 'transaction', type_='unique')
    op.create_unique_constraint('uq_transaction_source_external', 'transaction', ['account_id', 'source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    НЕОБРАТИМО начиная с первой законной пары "разные счета, общий external_id" —
    ровно то, ради чего эта миграция сделана (см. fix-ledger-unique-report.md).
    Старое ограничение UNIQUE(source, external_id) строже нового и не допускает
    такие пары: если хотя бы одна уже записана, наложить старое ограничение обратно
    нельзя без ручной чистки данных. Проверяем это явно и останавливаемся с понятным
    сообщением на русском вместо голого UniqueViolation из драйвера.
    """
    bind = op.get_bind()
    conflict = bind.execute(sa.text(
        """
        SELECT source, external_id, COUNT(DISTINCT account_id) AS accounts
        FROM transaction
        WHERE external_id IS NOT NULL
        GROUP BY source, external_id
        HAVING COUNT(DISTINCT account_id) > 1
        LIMIT 1
        """
    )).first()
    if conflict is not None:
        raise RuntimeError(
            "Откат миграции 0008 невозможен: в transaction уже есть операции с "
            f"одинаковым external_id ('{conflict.external_id}', source='{conflict.source}') "
            f"на {conflict.accounts} разных счетах. Именно такие пары были узаконены этой "
            "миграцией (см. fix-ledger-unique-report.md) — старое ограничение "
            "UNIQUE(source, external_id) их не допускает. Автоматический откат данные не "
            "трогает; чтобы продолжить, нужно вручную разобраться с этими строками "
            "(например, решить, какую из конфликтующих операций оставить) и повторить откат."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_source_external', 'transaction', type_='unique')
    op.create_unique_constraint(op.f('uq_transaction_source_external'), 'transaction', ['source', 'external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
