"""scope external id uniqueness per account

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-08 00:15:01.037818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    uq_transaction_source_external был (source, external_id) — глобальным по
    источнику. Живая синхронизация показала: T-Invest переиспользует один и тот же
    internal id для двух РАЗНЫХ записей на РАЗНЫХ счетах одного владельца (например,
    обе стороны перевода между своими счетами делят общий идентификатор — разбор в
    fix-ledger-unique-report.md). Такая пара — не дубль, но старое ограничение ложно
    считало её дублем и ронял весь батч синхронизации второго счёта. Область действия
    сужена до счёта: (account_id, source, external_id). Существующие данные не
    нарушают новое, более узкое ограничение — оно строго слабее старого (любая пара,
    уникальная по (source, external_id), остаётся уникальной и по (account_id, source,
    external_id)).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_transaction_source_external'), 'transaction', type_='unique')
    op.create_unique_constraint('uq_transaction_source_external', 'transaction', ['account_id', 'source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_source_external', 'transaction', type_='unique')
    op.create_unique_constraint(op.f('uq_transaction_source_external'), 'transaction', ['source', 'external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
